site_name: Synthesizer V Studio 非官方用户手册
site_url: https://zh.synthv.info/
site_description: SynthV Studio的非官方用户手册
site_author: Claire West,Blathroat
repo_url: https://github.com/claire-west/svstudio-manual-zh
copyright: <a href="#__consent">Change cookie settings</a>
nav:
  - 欢迎: index.md
  - 快速入门指南:
    - 安装和激活: setup.md
    - 工作区: workspace/layout.md
    - 编曲栏: workspace/arrangement.md
    - 钢琴卷帘: workspace/piano-roll.md
    - 侧面板: workspace/side-panels.md
    - 选择歌手: quickstart/singer-selection.md
    - 设置拍号和曲速: quickstart/setting-up-the-score.md
    - 添加音符: quickstart/creating-notes.md
    - 编辑音符: quickstart/editing-notes.md
    - 输入歌词: quickstart/entering-lyrics.md
    # - Introduction to Instant Mode: quickstart/instant-mode.md
    - 播放控件: quickstart/playback.md
    - 管理音轨: quickstart/managing-tracks.md
    - 导出音乐: quickstart/saving-the-audio.md
  - 音符属性:
    - 音高转变和颤音: note-properties/pitch-transition-and-vibrato.md
    - 编辑音素: note-properties/editing-phonemes.md
    - 音素和音符时长: note-properties/note-and-phoneme-timing.md
    - 备用音素和音素力度: note-properties/alternate-phonemes.md
    - 表现力分组: note-properties/expression-groups.md
  - 参数:
    - 参数面板: parameters/parameters-panel.md
    - 编辑参数: parameters/editing-parameters.md
    - 直接编辑音高偏差: parameters/direct-pitch-editing.md
    - 音调偏移: parameters/tone-shift.md
    - 声线参数: ai-functions/vocal-modes.md
  - 自动调校:
    - "音高模式：歌唱": ai-functions/pitch-mode-sing.md
    - "音高模式：说唱": ai-functions/pitch-mode-rap.md
    # - Instant Mode: ai-functions/instant-mode.md
    - AI重录: ai-functions/ai-retakes.md
    - 自动音高调校: ai-functions/auto-pitch-tuning.md
  - 中高级用法:
    - 手动音高模式: advanced/pitch-mode-manual.md
    - 批量输入歌词: advanced/batch-lyrics.md
    - 用户词典: advanced/user-dictionaries.md
    - 音符组: advanced/groups.md
    - 自动修饰音符: advanced/note-ornamentation.md
    - 音符偏移: advanced/note-detuning.md
    - MIDI设备支持: advanced/midi-controller.md
    - VSTi/AU插件: daw-integration/plugin.md
    - 顶部菜单: advanced/top-menus.md
    - 侧面板: advanced/side-panels.md
    - 右键菜单: advanced/right-click-menus.md
    - 脚本: advanced/scripting.md
  - 其他:
    - 常见问题: faq.md
    - 音素表: phonemes.md
    - 快捷键: keybinds.md
    - 帮助与支持: support.md
    - 关于: about.md
theme:
  name: material
  favicon: img/icon.ico
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: 切换至亮色模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: 切换至暗色模式
extra_css:
  - stylesheets/theme.css
plugins:
  - search:
      lang:
        - zh
        - en
  - exclude-search:
      exclude:
        - ai-functions/instant-mode.md
        - quickstart/instant-mode.md
  - social:
      cards_layout_options:
        background_color: "#2A2A2A"
        color: "#7DB235"
  - glightbox
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - macros
  - mkdocs-video:
      is_video: true
      css_style:
        width: "initial"
        height: "initial"
  - offline:
      enabled: !ENV [OFFLINE, false]
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys:
      key_map:
        mouse-wheel: "Mouse wheel"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  alternate:
    - name: 中文
      link: /
      lang: zh
    - name: English
      link: https://manual.synthv.info
      lang: en
  social:
    - icon: fontawesome/regular/comments
      link: https://forum.synthesizerv.com/t/topic/7524
      name: 在官方论坛上讨论此网站
    - icon: fontawesome/brands/github
      link: https://github.com/claire-west/svstudio-manual
      name: Github上的源代码
    - icon: simple/kofi
      link: https://ko-fi.com/claaaire
      name: 为此项目提供支持
  consent:
    title: Cookie设定
    description: >-
      我们使用cookies来跟踪并记录您的偏好，记录统计信息。我们通过每个页面上的“这个页面有用吗？”按钮收集反馈。在您同意的情况下帮助我们改进此文档。
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: 此页面有帮助吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 这个页面很有用ヾ(•ω•`)o
          data: 1
          note: >-
            感谢反馈ヾ(^▽^*)))
        - icon: material/emoticon-sad-outline
          name: 这个页面有待改进
          data: 0
          note: >-
            感谢反馈！您可以在<a href="https://forum.synthesizerv.com/t/topic/7524" target="_blank" rel="noopener">论坛</a>帮助我们改进。